version: '3'
services:
  next-auth-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: next-auth
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
